### PR TITLE
New code for the tax invoice number company that is in vietnam

### PR DESCRIPTION
**Pull request by fanha99**

### CODE REVIEW

**Comment by jcdrubay** [comment]
Please take into account the comment in #3 also you should not create a new PR, you just need to push new code to your previous branch.

**Comment by fanha99** [comment]
hi @jcdrubay,
because of the https://github.com/OCA/l10n-vietnam/pull/3 is fail because of codecov/patch and codecov/project test. really don't understand about that, so just make this PR for testing.

**Comment by jcdrubay** [comment]
#3 fails because it is the first module of the branch, I am not sure why you don't have those issues with this PR.

**Comment by fanha99** [comment]
with this PR, I'm just copy the code from the last commit of haidd, and continue from the brand 10.0 of the OCA/l10n-vietnam, not pick any commit from haidd brand.
this is the separate brand from the brand of the other PR.

**Comment by jcdrubay** [comment]
We should not do that because it will seems as if you are the only contributor ... :)
Then, I think that codecove is not checking if any test is missing on the first commit of a module, but it will from the second commit.
Anyway, we should close this PR.

**Pull request closed without merging**
